name: CD

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust (with Wasm targets)
      run: |
        set -e
        rustup update stable --no-self-update
        rustup default stable
        rustup target add wasm32-wasi
        rustup target add wasm32-unknown-unknown

    - name: Build Wasm
      run: cargo build --target wasm32-wasi --release

    - name: Build Extension
      run: |
        cp ./target/wasm32-wasi/release/{{cookiecutter.project_slug}}.wasm ./{{cookiecutter.project_slug}}.wasm
        tar cvf {{cookiecutter.project_slug}}.tar {{cookiecutter.project_slug}}.sql {{cookiecutter.project_slug}}.wasm {{cookiecutter.project_slug}}.wit 

    - name: Select Release Version
      id: versioning
      run: |
        VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="{{cookiecutter.project_slug}}") .version')
        echo "Version: $VERSION"
        echo "release_version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        title: "{{cookiecutter.project_slug}} ${{ "{{" }} steps.versioning.outputs.release_version {{ "}}" }}"
        repo_token: "${{ "{{" }} secrets.GITHUB_TOKEN {{ "}}" }}"
        automatic_release_tag: latest
        prerelease: false
        files: |
          {{cookiecutter.project_slug}}.tar
          {{cookiecutter.project_slug}}.sql
          {{cookiecutter.project_slug}}.wasm
          {{cookiecutter.project_slug}}.wit