name: CD

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust (with Wasm targets)
      run: |
        set -e
        rustup update stable --no-self-update
        rustup default stable
        rustup target add wasm32-wasi
        rustup target add wasm32-unknown-unknown

    - name: Build Wasm
      run: cargo build --target wasm32-wasi --release

    - name: Build Extension
      run: |
        cp ./target/wasm32-wasi/release/{{extension_name}}.wasm ./{{extension_name}}.wasm
        tar cvf {{extension_name}}.tar {{extension_name}}.sql {{extension_name}}.wasm {{extension_name}}.wit 

    - name: Select Release Version
      id: versioning
      run: |
        VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="{{extension_name}}") .version')
        echo "Version: $VERSION"
        echo "release_version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        title: "{{extension_name}} ${{ "{{" }} steps.versioning.outputs.release_version {{ "}}" }}"
        repo_token: "${{ "{{" }} secrets.GITHUB_TOKEN {{ "}}" }}"
        automatic_release_tag: latest
        prerelease: false
        files: |
          {{extension_name}}.tar
          {{extension_name}}.sql
          {{extension_name}}.wasm
          {{extension_name}}.wit